# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.3
     
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      PROFILE: full
      TEST_REPORTS: /tmp/test-reports
      
    steps:
      - checkout
        
      # run tests!
      - run: mvn test
      
      # copy TXT result to HTML report folder
      - run:
         cp ~/repo/./target/*.txt ~/repo/./target/tck-output

      # store test report folder as artifact
      - store_artifacts:
         path: ~/repo/./target/tck-output
workflows:
  version: 2
  test_tck:
    jobs:
      - build