# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      # - image: circleci/openjdk:8-jdk (Try to use Java 8)
      - image: cimg/openjdk:11.0.19
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      TEST_REPORTS: /tmp/test-reports
      
    steps:
      - checkout
        
      # run tests!
      - run: mvn test
      
      # copy TXT result to HTML report folder
      - run:
         cp ~/repo/./target/*.txt ~/repo/./target/tck-output

      # store test report folder as artifact
      - store_artifacts:
         path: ~/repo/./target/tck-output
         
workflows:
  version: 2
  test_tck:
    jobs:
      - test